version: '3.9'
services:
  # POSTGRE
  postgres14:
    container_name: postgresql14
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/data
    networks:
      - net_pg_pgadmin

  # PG ADMIN
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - type: bind
        source: ./data/pgadmin
        target: /var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - net_pg_pgadmin
    depends_on:
      - postgres14
      
networks:
  net_pg_pgadmin:
